### PR TITLE
Fix: make_credentials.sh uses passwords set in the .env file

### LINKED ISSUE #52: Unused passwords in docker setup
**Describe the bug**
Docker compose set up does not respect passwords given in .env file.

**Steps to reproduce**
Set a password for DB or BROKER, for ingest, finalize etc in the `.env` file (see our given [example](https://github.com/GenomicDataInfrastructure/starter-kit-storage-and-interfaces/blob/main/.env.example#L33-27)). When starting the docker stack, `make_credentials.sh` will ignore this and [set other passwords](https://github.com/GenomicDataInfrastructure/starter-kit-storage-and-interfaces/blob/main/scripts/make_credentials.sh#L16-L21).

**Expected behavior**
- [ ] Either make clear that these won't be used, or make the credentials script use them.
- [ ] Tests verifying the fix are added

**Additional context**

**Estimation of size**: small

**Estimation of priority**: medium

### PR DESCRIPTION
**Pull request by nanjiangshu**
This PR closes #52 

**How to test**
- Copy the file `.env.example` to  `.env`
- Modify some or all of the ENVs for `*_BROKER_PASSWORD` and `*_DB_PASSWORD`
- Start the docker setup by 
```
docker compose -f docker-compose-demo.yml up -d 
```
- Check if the docker setup runs properly and if the following commands returns meaningful results and the file `htsnexus_test_NA12878.bam` is downloaded
```
token=$(curl -s -k https://localhost:8080/tokens | jq -r '.[0]')
curl -s -H "Authorization: Bearer $token" http://localhost:8443/metadata/datasets | jq .
datasetID=DATASET0001
filename="htsnexus_test_NA12878.bam"
curl -s -H "Authorization: Bearer $token" http://localhost:8443/metadata/datasets/$datasetID/files  
curl -s -H "Authorization: Bearer $token" http://localhost:8443/s3/$datasetID/$filename -o "$filename"
```

### CODE REVIEW

File: scripts/make_credentials.sh [hunk 1]
```diff
@@ -12,13 +12,19 @@ pip install aiohttp Authlib joserfc requests > /dev/null
...
 for n in download finalize inbox ingest mapper sync verify; do
     echo "creating credentials for: $n"
-    ## password and permissions for MQ
-    body_data=$(jq -n -c --arg password "$n" --arg tags none '$ARGS.named')
+    db_password=$(eval echo \$$n"_DB_PASSWORD")
+    mq_password=$(eval echo \$$n"_BROKER_PASSWORD")
+    db_password=${db_password:-$n}
+    mq_password=${mq_password:-$n}
+
+    echo "role: $n, db password: $db_password, mq password: $mq_password"
```
Comment (aaperis) [inline scripts/make_credentials.sh]:
```suggestion
 ```
It seems like bad practice to print out credentials.

Comment (nanjiangshu) [reply scripts/make_credentials.sh]: I believed I have deleted this line but it was still there. Fixed in dee03a7

**Review by aaperis — APPROVED** [review]

**Review by kostas-kou — APPROVED** [review]
